name: contact_api
description: The interface and models for an API providing access to contacts.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter
