name: flutter_contact
description: An example contact app that showcases bloc state management patterns..
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  local_storage_contact_api:
    path: packages/local_storage_contact_api
  contact_api:
    path: packages/contact_api
  contacts_repository:
    path: packages/contacts_repository     

  bloc: ^8.1.2
  bloc_effects: ^1.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  formz: ^0.6.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
